# Generated by Django 2.1.1 on 2018-10-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePage', '0002_auto_20181004_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectdate',
            name='likeNum',
            field=models.IntegerField(default=0),
        ),
    ]
