# Generated by Django 2.1.1 on 2018-10-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePage', '0003_auto_20181004_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectdate',
            old_name='likeNum',
            new_name='confirmIndicator',
        ),
        migrations.RenameField(
            model_name='selectdate',
            old_name='selectedDate',
            new_name='selectDate',
        ),
        migrations.RemoveField(
            model_name='selectdate',
            name='saveDate',
        ),
        migrations.AddField(
            model_name='selectdate',
            name='dateCount',
            field=models.IntegerField(default=0),
        ),
    ]
