# Generated by Django 2.1.1 on 2018-11-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePage', '0004_auto_20181004_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamPlanNo', models.IntegerField(default=0)),
                ('selectDate', models.CharField(max_length=10)),
                ('userId', models.CharField(max_length=10)),
                ('pickCount', models.IntegerField()),
                ('userColor', models.CharField(max_length=10)),
                ('lat', models.IntegerField(default=0)),
                ('lng', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=10)),
                ('confirm', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=10)),
                ('userId', models.CharField(max_length=10)),
                ('leader', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemaPlanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=10)),
                ('teamPlanNo', models.IntegerField(default=0)),
                ('teamPlanName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('userPw', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('teamCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='selectdate',
            name='teamPlanNo',
            field=models.IntegerField(default=0),
        ),
    ]
