# Generated by Django 2.1.2 on 2018-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePage', '0005_auto_20181105_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temaplanlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='temaplanlist',
            name='teamPlanNo',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
