# Generated by Django 2.1.2 on 2018-11-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePage', '0006_auto_20181110_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temaplanlist',
            name='teamPlanNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
